import { useState } from "react";
import { X, Share2, MessageCircle, Mail, CheckCircle, AlertCircle, Copy, Check } from "lucide-react";
import type { Property, ComplianceStatus, VaultDocument } from "@/types/property";

interface Props {
  property: Property;
  documents: VaultDocument[];
  onClose: () => void;
}

const COMPLIANCE_LABELS: Record<keyof ComplianceStatus, string> = {
  gasSafety: "Gas Safety Certificate",
  eicr: "EICR (Electrical Safety)",
  epc: "Energy Performance Certificate",
  rentersRightsAct2026: "Renters' Rights Act 2026",
  tenantInfoStatement: "Tenant Information Statement",
};

const DOC_TYPE_MAP: Record<string, keyof ComplianceStatus> = {
  gas: "gasSafety",
  eicr: "eicr",
  epc: "epc",
  "tenant-info": "tenantInfoStatement",
};

const TenantPackModal = ({ property, documents, onClose }: Props) => {
  const [copied, setCopied] = useState(false);

  const compliantItems = (Object.entries(property.compliance) as [keyof ComplianceStatus, boolean][])
    .filter(([, v]) => v);

  const nonCompliantItems = (Object.entries(property.compliance) as [keyof ComplianceStatus, boolean][])
    .filter(([, v]) => !v);

  const propertyDocs = documents.filter((d) => d.propertyId === property.id);

  const compliantDocs = propertyDocs.filter((d) => {
    const field = DOC_TYPE_MAP[d.type];
    return field ? property.compliance[field] : false;
  });

  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const packText = [
    `🏠 TENANT COMPLIANCE PACK`,
    `Property: ${property.address}`,
    `Generated: ${today}`,
    ``,
    `✅ COMPLIANT (${compliantItems.length}/${compliantItems.length + nonCompliantItems.length})`,
    ...compliantItems.map(([key]) => `  • ${COMPLIANCE_LABELS[key]}`),
    ...(compliantDocs.length > 0
      ? [``, `📄 CERTIFICATES ON FILE`, ...compliantDocs.map((d) => `  • ${d.name}`)]
      : []),
    ...(nonCompliantItems.length > 0
      ? [
          ``,
          `⚠️ PENDING (${nonCompliantItems.length})`,
          ...nonCompliantItems.map(([key]) => `  • ${COMPLIANCE_LABELS[key]}`),
        ]
      : []),
    ``,
    `Generated by Landy — Property Compliance Made Simple`,
  ].join("\n");

  const encodedText = encodeURIComponent(packText);

  const shareWhatsApp = () => {
    window.open(`https://wa.me/?text=${encodedText}`, "_blank");
  };

  const shareEmail = () => {
    const subject = encodeURIComponent(`Tenant Compliance Pack — ${property.address}`);
    window.open(`mailto:?subject=${subject}&body=${encodedText}`, "_blank");
  };

  const shareNative = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Tenant Pack — ${property.address}`,
          text: packText,
        });
      } catch {
        // User cancelled
      }
    }
  };

  const copyToClipboard = async () => {
    await navigator.clipboard.writeText(packText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/40 backdrop-blur-sm">
      <div className="w-full max-w-lg bg-card rounded-t-2xl sm:rounded-2xl border border-border shadow-xl max-h-[90vh] overflow-y-auto">
        {/* Header */}
        <div className="flex items-center justify-between px-5 py-4 border-b border-border">
          <h2 className="text-base font-semibold text-foreground">Tenant Compliance Pack</h2>
          <button onClick={onClose} className="p-1 rounded-lg hover:bg-muted transition-colors">
            <X className="w-5 h-5 text-muted-foreground" />
          </button>
        </div>

        <div className="p-5 space-y-4">
          {/* Property */}
          <div className="rounded-xl border border-border bg-muted/30 px-4 py-3">
            <p className="text-xs text-muted-foreground">Property</p>
            <p className="text-sm font-medium text-foreground">{property.address}</p>
            <p className="text-xs text-muted-foreground mt-1">{today}</p>
          </div>

          {/* Compliant items */}
          {compliantItems.length > 0 && (
            <div>
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
                Compliant ({compliantItems.length})
              </h3>
              <div className="space-y-1.5">
                {compliantItems.map(([key]) => (
                  <div
                    key={key}
                    className="flex items-center gap-2.5 px-3 py-2 rounded-lg bg-primary/8 border border-primary/15"
                  >
                    <CheckCircle className="w-4 h-4 text-primary shrink-0" />
                    <span className="text-sm text-foreground">{COMPLIANCE_LABELS[key]}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Pending items */}
          {nonCompliantItems.length > 0 && (
            <div>
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
                Pending ({nonCompliantItems.length})
              </h3>
              <div className="space-y-1.5">
                {nonCompliantItems.map(([key]) => (
                  <div
                    key={key}
                    className="flex items-center gap-2.5 px-3 py-2 rounded-lg"
                    style={{ background: "hsl(var(--risk-warm) / 0.08)", border: "1px solid hsl(var(--risk-warm) / 0.15)" }}
                  >
                    <AlertCircle className="w-4 h-4 shrink-0" style={{ color: "hsl(var(--risk-warm))" }} />
                    <span className="text-sm text-foreground">{COMPLIANCE_LABELS[key]}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Certificates on file */}
          {compliantDocs.length > 0 && (
            <div>
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-2">
                Certificates on File ({compliantDocs.length})
              </h3>
              <div className="space-y-1.5">
                {compliantDocs.map((doc) => (
                  <div
                    key={doc.id}
                    className="flex items-center gap-2.5 px-3 py-2 rounded-lg bg-muted/50 border border-border"
                  >
                    <span className="text-sm text-foreground">{doc.name}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Share buttons */}
          <div className="space-y-2 pt-2">
            <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
              Share Pack
            </h3>

            <div className="grid grid-cols-2 gap-2">
              <button
                onClick={shareWhatsApp}
                className="flex items-center justify-center gap-2 rounded-lg bg-[#25D366]/10 px-4 py-3 text-sm font-medium text-[#25D366] hover:bg-[#25D366]/20 transition-colors"
              >
                <MessageCircle className="w-4 h-4" />
                WhatsApp
              </button>
              <button
                onClick={shareEmail}
                className="flex items-center justify-center gap-2 rounded-lg bg-primary/10 px-4 py-3 text-sm font-medium text-primary hover:bg-primary/20 transition-colors"
              >
                <Mail className="w-4 h-4" />
                Email
              </button>
            </div>

            <div className="grid grid-cols-2 gap-2">
              {typeof navigator.share === "function" && (
                <button
                  onClick={shareNative}
                  className="flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-3 text-sm font-medium text-foreground hover:bg-muted transition-colors"
                >
                  <Share2 className="w-4 h-4" />
                  Share
                </button>
              )}
              <button
                onClick={copyToClipboard}
                className="flex items-center justify-center gap-2 rounded-lg border border-border px-4 py-3 text-sm font-medium text-foreground hover:bg-muted transition-colors"
              >
                {copied ? <Check className="w-4 h-4 text-primary" /> : <Copy className="w-4 h-4" />}
                {copied ? "Copied!" : "Copy"}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TenantPackModal;
