// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyitvzqjexmpbulbaopw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5aXR2enFqZXhtcGJ1bGJhb3B3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMDE4MjgsImV4cCI6MjA4NjY3NzgyOH0.mdGp7my5N40Apr540s2fe0_YFH5uV9MaJysn7g1-0jQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});